product-project/movie/movieproject/movieapp/urls.py
from django.urls import path

from movieapp import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

product-project/movie/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product-project/movie/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

product-project/movie/movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

product-project/movie/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from movieapp.forms import MovieForm
from movieapp.models import Movie
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
        }
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

    # return HttpResponse("this is movies no %s" % movie_id)

product-project/movie/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter movie name">
  <input type="text" name="desc" placeholder="enter movie description">
  <input type="text" name="year" placeholder="enter movie year">
  <input type="file" name="img">
  <input type="submit">
</form>
{% endblock %}

product-project/movie/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      online movies
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

product-project/movie/movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you wanna delete this movie?
  <input type="submit">
</form>

product-project/movie/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>

<div class="col-md-6">
    <h2>{{movie.name}}</h2>
    <h4>{{movie.desc}}</h4>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
</div>

   </div>
</div>
{% endblock %}

product-project/movie/movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

product-project/movie/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt=" " width="100px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

<!--{{i.id}} &ndash;&gt; {{i.name}}  <br>-->
<!--<a href="movie/{{i.id}}">{{i.name}}<br>-->